services:
  udp-responder:
    build:
      context: .
      network: host
    container_name: udp-responder
    command: ["python", "-u", "udp_server_secure.py"]
    restart: always
    network_mode: "host"
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

  db:
    image: postgres:15-alpine
    container_name: iot-db
    restart: always
    env_file: .env
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web-ui:
    build:
      context: .
      network: host
    container_name: web-ui
    network_mode: "host"
    restart: always
    env_file: .env
    environment:
      # Use Host binding so localhost seamlessly bridges to the physical OS MQTT Broker natively
      - DB_HOST=127.0.0.1
      - DB_PORT=5433
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

volumes:
  postgres_data:
